### ISSUE TITLE
Failure within multicall: TypeError: Cannot convert None of type <class 'NoneType'> to bytes

### ISSUE THREAD

**Issue by miohtama** [banteg/multicall.py#103]
I am getting the following traceback within the multicall library.

What happens is that `fetch_outputs` tries to format the output from the result. However this format operation fails, for some reason there is `None` where there should be `bytes`.  I believe this is either due to ABI mismatch or RPC error. However what makes this difficult to handle is that the whole multicall operation fails and the handler is not called - there is no way to isolate this and nicely handle this.

Asking for an advise what would be the best way to tackle this.

[Here is the relevant source code](https://github.com/tradingstrategy-ai/web3-ethereum-defi/blob/af0f3cb47bd563b14b8c673b97e815425b317c08/eth_defi/balances.py#L232).

```
Traceback (most recent call last):
  File "/usr/src/trade-executor/tradeexecutor/cli/loop.py", line 1169, in live_cycle
    universe = self.tick(
               ^^^^^^^^^^
  File "/usr/src/trade-executor/tradeexecutor/cli/loop.py", line 544, in tick
    self.runner.check_balances_post_execution(
  File "/usr/src/trade-executor/tradeexecutor/strategy/runner.py", line 610, in check_balances_post_execution
    self.check_accounts(
  File "/usr/src/trade-executor/tradeexecutor/strategy/runner.py", line 1024, in check_accounts
    clean, df = check_accounts(
                ^^^^^^^^^^^^^^^
  File "/usr/src/trade-executor/tradeexecutor/strategy/account_correction.py", line 936, in check_accounts
    for c in corrections:
  File "/usr/src/trade-executor/tradeexecutor/strategy/account_correction.py", line 301, in calculate_account_corrections
    asset_balances = list(asset_balances)
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/trade-executor/tradeexecutor/ethereum/onchain_balance.py", line 66, in fetch_address_balances
    balances = fetch_erc20_balances_multicall(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/trade-executor/deps/web3-ethereum-defi/eth_defi/balances.py", line 356, in fetch_erc20_balances_multicall
    batched_result = multicall()
                     ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/multicall/multicall.py", line 58, in __call__
    response = await_awaitable(self)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/multicall/utils.py", line 75, in await_awaitable
    return get_event_loop().run_until_complete(awaitable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 694, in _wrap_awaitable
    return (yield from awaitable.__await__())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/multicall/multicall.py", line 66, in coroutine
    batches = await gather([
              ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/multicall/utils.py", line 92, in gather
    raise_if_exception_in(results)
  File "/usr/local/lib/python3.11/site-packages/multicall/utils.py", line 88, in raise_if_exception_in
    raise_if_exception(obj)
  File "/usr/local/lib/python3.11/site-packages/multicall/utils.py", line 84, in raise_if_exception
    raise obj
  File "/usr/local/lib/python3.11/site-packages/multicall/multicall.py", line 99, in fetch_outputs
    _raise_or_proceed(e, len(calls), ConnErr_retries=ConnErr_retries)
  File "/usr/local/lib/python3.11/site-packages/multicall/multicall.py", line 213, in _raise_or_proceed
    raise e
  File "/usr/local/lib/python3.11/site-packages/multicall/multicall.py", line 91, in fetch_outputs
    self.block_id, _, outputs = await self.aggregate.coroutine(args)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/eth_retry/eth_retry.py", line 84, in auto_retry_wrap_async
    return await func(*args,**kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/multicall/call.py", line 116, in coroutine
    output = await get_async_w3(_w3).eth.call(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/eth/async_eth.py", line 270, in call
    return await self._durin_call(transaction, block_identifier, state_override)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/eth/async_eth.py", line 289, in _durin_call
    return await self._call(transaction, block_identifier, state_override)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/module.py", line 121, in caller
    return apply_result_formatters(result_formatters, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cytoolz/functoolz.pyx", line 272, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 268, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.11/site-packages/web3/module.py", line 49, in apply_result_formatters
    formatted_result = pipe(result, result_formatters)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cytoolz/functoolz.pyx", line 685, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 660, in cytoolz.functoolz.c_pipe
  File "/usr/local/lib/python3.11/site-packages/hexbytes/main.py", line 42, in __new__
    bytesval = to_bytes(val)
               ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hexbytes/_utils.py", line 32, in to_bytes
    raise TypeError(f"Cannot convert {val!r} of type {type(val)} to bytes")
TypeError: Cannot convert None of type <class 'NoneType'> to bytes
```

**Comment by BobTheBuidler** [comment]
I'm not sure this is the best place to discuss this. You should open an issue in web3.py. Going to close this, feel free to reopen if there is more reason to believe there is an issue in multicall lib specifically.
